version: "3.8"
services:
  node:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: sh -c 'node'
    ports:
      - "5000:5000"
    tty: true
    volumes:
      - "./:/home/node/app"
    working_dir: /home/node/app
